version: "3.9"

services:
  db:
    image: postgres:14.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "hashit", "-U", "hashit"]
      timeout: 5s
      interval: 10s
      retries: 5
    restart: always
    environment:
      - POSTGRES_PASSWORD=hashit
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./.docker/db:/docker-entrypoint-initdb.d/
