version: 2.1

jobs:
  format:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Restore dotnet tools
          command: dotnet tool restore

      - run:
          name: Check formatting
          command: dotnet csharpier . --check

  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            dotnet test -c release

  integration-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
      - image: postgres:14.2-alpine
        environment:
          POSTGRES_PASSWORD: hashit
    steps:
      - checkout

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1

      - run:
          name: Run integration tests
          command: |
            dotnet test ./test-integration -c release

workflows:
  ci:
    jobs:
      - format
      - build-and-test
      - integration-test
