version: 2.1

jobs:
  format:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Restore dotnet tools
          command: dotnet tool restore

      - run:
          name: Check formatting
          command: dotnet csharpier . --check

  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            dotnet test -c release

  integration-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: "2.9.0"
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build

      - run:
          name: Start docker-compose and verify service(s)
          command: |
            docker-compose up -d

            docker container run --network container:postgres \
              docker.io/jwilder/dockerize \
              -wait tcp://localhost:5432 \
              -wait-retry-interval 2s \
              -timeout 1m
      - run:
          name: Run integration tests
          command: |
            dotnet test test-integration/Hashit.Integration.sln -c release

workflows:
  ci:
    jobs:
      - format
      - build-and-test
      - integration-test
