version: 2.1

jobs:
  format:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Restore dotnet tools
          command: dotnet tool restore

      - run:
          name: Check formatting
          command: dotnet csharpier . --check

  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            dotnet test -c release

  integration-test:
    docker:
      - image: cimg/base:current
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build

      - run:
          name: Start docker-compose and verify service(s)
          command: |
            # Setting the Docker Compose project name to "hashit-backend"
            # the names of our services' containers would be prefixed with "hashit-backend".
            docker-compose -p hashit-backend up -d

            # Check of postgresql is ready
            docker container run --network container:hashit-backend_postgres_1 \
              docker.io/jwilder/dockerize \
              -wait tcp://localhost:5432 \
              -wait-retry-interval 2s \
              -timeout 1m
      - run:
          name: Run integration tests
          command: |
            dotnet test test-integration/Hashit.Integration.sln -c release

workflows:
  ci:
    jobs:
      - format
      - build-and-test
      - integration-test
