version: 2.1

orbs:
  docker: circleci/docker@2.1.2

jobs:
  format:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Restore dotnet tools
          command: dotnet tool restore

      - run:
          name: Check formatting
          command: dotnet csharpier . --check

  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            dotnet test -c release

  integration-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
      - image: postgres:14.2-alpine
    steps:
      - checkout
      - docker/install-dockerize

      - run:
          name: Wait for postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run integration tests
          command: |
            dotnet test ./test-integration -c release

workflows:
  ci:
    jobs:
      - format
      - build-and-test
      - integration-test
