version: 2.1

orbs:
  docker: circleci/docker@2.1.2
  jq: circleci/jq@2.2.0

jobs:
  format:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Restore dotnet tools
          command: dotnet tool restore

      - run:
          name: Check formatting
          command: dotnet csharpier . --check

  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            dotnet test -c release

  integration-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - jq/install
      - docker/install-docker-tools

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build

      - run:
          name: Start docker-compose and verify service(s)
          command: |
            docker-compose up -d

            docker container run --network container:postgres \
              docker.io/jwilder/dockerize \
              -wait tcp://localhost:5432 \
              -wait-retry-interval 2s \
              -timeout 1m

      - run:
          working_directory: ~/test-integration
          name: Run integration tests
          command: |
            dotnet test -c release

workflows:
  ci:
    jobs:
      - format
      - build-and-test
      - integration-test
