name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  DOTNET_VERSION: "6.0.x"

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
      - uses: actions/checkout@v2
      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Check formatting
        run: dotnet csharpier --check
  build-and-unit-test:
    runs-on: ubuntu-latest
    name: Build and run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install package dependencies
        run: dotnet restore Hashit.sln

      - name: Build
        run: dotnet build Hashit.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Hashit.sln --no-restore --verbosity normal
  integration-test:
    runs-on: ubuntu-latest
    name: Run integration tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Start docker
        run: docker-compose up -d
      - name: Install package dependencies
        run: dotnet restore Hashit.IntegrationTests.sln

      - name: Build
        run: dotnet build Hashit.IntegrationTests.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Hashit.IntegrationTests.sln --no-restore --verbosity normal
